// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Activity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nova.Client {

  /// <summary>Holder for reflection information generated from Activity.proto</summary>
  public static partial class ActivityReflection {

    #region Descriptor
    /// <summary>File descriptor for Activity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActivityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5BY3Rpdml0eS5wcm90byLGAgoIQWN0aXZpdHkSCgoCaWQYASABKAUSDwoH",
            "c29ydF9pZBgCIAEoBRIVCg1hY3Rpdml0eV90eXBlGAMgASgFEgwKBG5hbWUY",
            "BCABKAkSEQoJcHJlX2xpbWl0GAUgASgFEhMKC2xpbWl0X3BhcmFtGAYgASgJ",
            "EhIKCnN0YXJ0X3R5cGUYByABKAUSEgoKc3RhcnRfdGltZRgIIAEoCRIXCg9z",
            "dGFydF9jb25kX3R5cGUYCSABKAUSGQoRc3RhcnRfY29uZF9wYXJhbXMYCiAD",
            "KAUSEAoIZW5kX3R5cGUYCyABKAUSEAoIZW5kX3RpbWUYDCABKAkSFAoMZW5k",
            "X2R1cmF0aW9uGA0gASgFEhIKCmJhbm5lcl9yZXMYDiABKAkSEgoKcG9wX3Vw",
            "X3JlcxgPIAEoCRISCgp0YWJfYmdfcmVzGBAgASgJQg6qAgtOb3ZhLkNsaWVu",
            "dGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nova.Client.Activity), global::Nova.Client.Activity.Parser, new[]{ "Id", "SortId", "ActivityType", "Name", "PreLimit", "LimitParam", "StartType", "StartTime", "StartCondType", "StartCondParams", "EndType", "EndTime", "EndDuration", "BannerRes", "PopUpRes", "TabBgRes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Activity : pb::IMessage<Activity>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Activity> _parser = new pb::MessageParser<Activity>(() => new Activity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Activity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nova.Client.ActivityReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Activity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Activity(Activity other) : this() {
      id_ = other.id_;
      sortId_ = other.sortId_;
      activityType_ = other.activityType_;
      name_ = other.name_;
      preLimit_ = other.preLimit_;
      limitParam_ = other.limitParam_;
      startType_ = other.startType_;
      startTime_ = other.startTime_;
      startCondType_ = other.startCondType_;
      startCondParams_ = other.startCondParams_.Clone();
      endType_ = other.endType_;
      endTime_ = other.endTime_;
      endDuration_ = other.endDuration_;
      bannerRes_ = other.bannerRes_;
      popUpRes_ = other.popUpRes_;
      tabBgRes_ = other.tabBgRes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Activity Clone() {
      return new Activity(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "sort_id" field.</summary>
    public const int SortIdFieldNumber = 2;
    private int sortId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SortId {
      get { return sortId_; }
      set {
        sortId_ = value;
      }
    }

    /// <summary>Field number for the "activity_type" field.</summary>
    public const int ActivityTypeFieldNumber = 3;
    private int activityType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ActivityType {
      get { return activityType_; }
      set {
        activityType_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pre_limit" field.</summary>
    public const int PreLimitFieldNumber = 5;
    private int preLimit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PreLimit {
      get { return preLimit_; }
      set {
        preLimit_ = value;
      }
    }

    /// <summary>Field number for the "limit_param" field.</summary>
    public const int LimitParamFieldNumber = 6;
    private string limitParam_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LimitParam {
      get { return limitParam_; }
      set {
        limitParam_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "start_type" field.</summary>
    public const int StartTypeFieldNumber = 7;
    private int startType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StartType {
      get { return startType_; }
      set {
        startType_ = value;
      }
    }

    /// <summary>Field number for the "start_time" field.</summary>
    public const int StartTimeFieldNumber = 8;
    private string startTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StartTime {
      get { return startTime_; }
      set {
        startTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "start_cond_type" field.</summary>
    public const int StartCondTypeFieldNumber = 9;
    private int startCondType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StartCondType {
      get { return startCondType_; }
      set {
        startCondType_ = value;
      }
    }

    /// <summary>Field number for the "start_cond_params" field.</summary>
    public const int StartCondParamsFieldNumber = 10;
    private static readonly pb::FieldCodec<int> _repeated_startCondParams_codec
        = pb::FieldCodec.ForInt32(82);
    private readonly pbc::RepeatedField<int> startCondParams_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> StartCondParams {
      get { return startCondParams_; }
    }

    /// <summary>Field number for the "end_type" field.</summary>
    public const int EndTypeFieldNumber = 11;
    private int endType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EndType {
      get { return endType_; }
      set {
        endType_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 12;
    private string endTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EndTime {
      get { return endTime_; }
      set {
        endTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "end_duration" field.</summary>
    public const int EndDurationFieldNumber = 13;
    private int endDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EndDuration {
      get { return endDuration_; }
      set {
        endDuration_ = value;
      }
    }

    /// <summary>Field number for the "banner_res" field.</summary>
    public const int BannerResFieldNumber = 14;
    private string bannerRes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BannerRes {
      get { return bannerRes_; }
      set {
        bannerRes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pop_up_res" field.</summary>
    public const int PopUpResFieldNumber = 15;
    private string popUpRes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PopUpRes {
      get { return popUpRes_; }
      set {
        popUpRes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tab_bg_res" field.</summary>
    public const int TabBgResFieldNumber = 16;
    private string tabBgRes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TabBgRes {
      get { return tabBgRes_; }
      set {
        tabBgRes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Activity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Activity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (SortId != other.SortId) return false;
      if (ActivityType != other.ActivityType) return false;
      if (Name != other.Name) return false;
      if (PreLimit != other.PreLimit) return false;
      if (LimitParam != other.LimitParam) return false;
      if (StartType != other.StartType) return false;
      if (StartTime != other.StartTime) return false;
      if (StartCondType != other.StartCondType) return false;
      if(!startCondParams_.Equals(other.startCondParams_)) return false;
      if (EndType != other.EndType) return false;
      if (EndTime != other.EndTime) return false;
      if (EndDuration != other.EndDuration) return false;
      if (BannerRes != other.BannerRes) return false;
      if (PopUpRes != other.PopUpRes) return false;
      if (TabBgRes != other.TabBgRes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (SortId != 0) hash ^= SortId.GetHashCode();
      if (ActivityType != 0) hash ^= ActivityType.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (PreLimit != 0) hash ^= PreLimit.GetHashCode();
      if (LimitParam.Length != 0) hash ^= LimitParam.GetHashCode();
      if (StartType != 0) hash ^= StartType.GetHashCode();
      if (StartTime.Length != 0) hash ^= StartTime.GetHashCode();
      if (StartCondType != 0) hash ^= StartCondType.GetHashCode();
      hash ^= startCondParams_.GetHashCode();
      if (EndType != 0) hash ^= EndType.GetHashCode();
      if (EndTime.Length != 0) hash ^= EndTime.GetHashCode();
      if (EndDuration != 0) hash ^= EndDuration.GetHashCode();
      if (BannerRes.Length != 0) hash ^= BannerRes.GetHashCode();
      if (PopUpRes.Length != 0) hash ^= PopUpRes.GetHashCode();
      if (TabBgRes.Length != 0) hash ^= TabBgRes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (SortId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SortId);
      }
      if (ActivityType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ActivityType);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (PreLimit != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(PreLimit);
      }
      if (LimitParam.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(LimitParam);
      }
      if (StartType != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(StartType);
      }
      if (StartTime.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(StartTime);
      }
      if (StartCondType != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(StartCondType);
      }
      startCondParams_.WriteTo(output, _repeated_startCondParams_codec);
      if (EndType != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(EndType);
      }
      if (EndTime.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(EndTime);
      }
      if (EndDuration != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(EndDuration);
      }
      if (BannerRes.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(BannerRes);
      }
      if (PopUpRes.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(PopUpRes);
      }
      if (TabBgRes.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(TabBgRes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (SortId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SortId);
      }
      if (ActivityType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ActivityType);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (PreLimit != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(PreLimit);
      }
      if (LimitParam.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(LimitParam);
      }
      if (StartType != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(StartType);
      }
      if (StartTime.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(StartTime);
      }
      if (StartCondType != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(StartCondType);
      }
      startCondParams_.WriteTo(ref output, _repeated_startCondParams_codec);
      if (EndType != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(EndType);
      }
      if (EndTime.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(EndTime);
      }
      if (EndDuration != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(EndDuration);
      }
      if (BannerRes.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(BannerRes);
      }
      if (PopUpRes.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(PopUpRes);
      }
      if (TabBgRes.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(TabBgRes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (SortId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SortId);
      }
      if (ActivityType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActivityType);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (PreLimit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PreLimit);
      }
      if (LimitParam.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LimitParam);
      }
      if (StartType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartType);
      }
      if (StartTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StartTime);
      }
      if (StartCondType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartCondType);
      }
      size += startCondParams_.CalculateSize(_repeated_startCondParams_codec);
      if (EndType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EndType);
      }
      if (EndTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EndTime);
      }
      if (EndDuration != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EndDuration);
      }
      if (BannerRes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BannerRes);
      }
      if (PopUpRes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PopUpRes);
      }
      if (TabBgRes.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(TabBgRes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Activity other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.SortId != 0) {
        SortId = other.SortId;
      }
      if (other.ActivityType != 0) {
        ActivityType = other.ActivityType;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.PreLimit != 0) {
        PreLimit = other.PreLimit;
      }
      if (other.LimitParam.Length != 0) {
        LimitParam = other.LimitParam;
      }
      if (other.StartType != 0) {
        StartType = other.StartType;
      }
      if (other.StartTime.Length != 0) {
        StartTime = other.StartTime;
      }
      if (other.StartCondType != 0) {
        StartCondType = other.StartCondType;
      }
      startCondParams_.Add(other.startCondParams_);
      if (other.EndType != 0) {
        EndType = other.EndType;
      }
      if (other.EndTime.Length != 0) {
        EndTime = other.EndTime;
      }
      if (other.EndDuration != 0) {
        EndDuration = other.EndDuration;
      }
      if (other.BannerRes.Length != 0) {
        BannerRes = other.BannerRes;
      }
      if (other.PopUpRes.Length != 0) {
        PopUpRes = other.PopUpRes;
      }
      if (other.TabBgRes.Length != 0) {
        TabBgRes = other.TabBgRes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            SortId = input.ReadInt32();
            break;
          }
          case 24: {
            ActivityType = input.ReadInt32();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 40: {
            PreLimit = input.ReadInt32();
            break;
          }
          case 50: {
            LimitParam = input.ReadString();
            break;
          }
          case 56: {
            StartType = input.ReadInt32();
            break;
          }
          case 66: {
            StartTime = input.ReadString();
            break;
          }
          case 72: {
            StartCondType = input.ReadInt32();
            break;
          }
          case 82:
          case 80: {
            startCondParams_.AddEntriesFrom(input, _repeated_startCondParams_codec);
            break;
          }
          case 88: {
            EndType = input.ReadInt32();
            break;
          }
          case 98: {
            EndTime = input.ReadString();
            break;
          }
          case 104: {
            EndDuration = input.ReadInt32();
            break;
          }
          case 114: {
            BannerRes = input.ReadString();
            break;
          }
          case 122: {
            PopUpRes = input.ReadString();
            break;
          }
          case 130: {
            TabBgRes = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            SortId = input.ReadInt32();
            break;
          }
          case 24: {
            ActivityType = input.ReadInt32();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 40: {
            PreLimit = input.ReadInt32();
            break;
          }
          case 50: {
            LimitParam = input.ReadString();
            break;
          }
          case 56: {
            StartType = input.ReadInt32();
            break;
          }
          case 66: {
            StartTime = input.ReadString();
            break;
          }
          case 72: {
            StartCondType = input.ReadInt32();
            break;
          }
          case 82:
          case 80: {
            startCondParams_.AddEntriesFrom(ref input, _repeated_startCondParams_codec);
            break;
          }
          case 88: {
            EndType = input.ReadInt32();
            break;
          }
          case 98: {
            EndTime = input.ReadString();
            break;
          }
          case 104: {
            EndDuration = input.ReadInt32();
            break;
          }
          case 114: {
            BannerRes = input.ReadString();
            break;
          }
          case 122: {
            PopUpRes = input.ReadString();
            break;
          }
          case 130: {
            TabBgRes = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
