// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Chapter.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nova.Client {

  /// <summary>Holder for reflection information generated from Chapter.proto</summary>
  public static partial class ChapterReflection {

    #region Descriptor
    /// <summary>File descriptor for Chapter.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChapterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1DaGFwdGVyLnByb3RvIrkBCgdDaGFwdGVyEgoKAmlkGAEgASgFEgwKBG5h",
            "bWUYAiABKAkSDAoEZGVzYxgDIAEoCRIUCgxjaGFwdGVyX3R5cGUYBCABKAUS",
            "EwoLd29ybGRfY2xhc3MYBSABKAUSFgoOcHJldl9tYWlubGluZXMYBiADKAUS",
            "GAoQY29tcGxldGVfcmV3YXJkcxgHIAEoCRITCgtjaGFwdGVyX2ltZxgIIAEo",
            "CRIUCgxjaGFwdGVyX2ljb24YCSABKAlCDqoCC05vdmEuQ2xpZW50YgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nova.Client.Chapter), global::Nova.Client.Chapter.Parser, new[]{ "Id", "Name", "Desc", "ChapterType", "WorldClass", "PrevMainlines", "CompleteRewards", "ChapterImg", "ChapterIcon" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Chapter : pb::IMessage<Chapter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Chapter> _parser = new pb::MessageParser<Chapter>(() => new Chapter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Chapter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nova.Client.ChapterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Chapter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Chapter(Chapter other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      desc_ = other.desc_;
      chapterType_ = other.chapterType_;
      worldClass_ = other.worldClass_;
      prevMainlines_ = other.prevMainlines_.Clone();
      completeRewards_ = other.completeRewards_;
      chapterImg_ = other.chapterImg_;
      chapterIcon_ = other.chapterIcon_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Chapter Clone() {
      return new Chapter(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 3;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chapter_type" field.</summary>
    public const int ChapterTypeFieldNumber = 4;
    private int chapterType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChapterType {
      get { return chapterType_; }
      set {
        chapterType_ = value;
      }
    }

    /// <summary>Field number for the "world_class" field.</summary>
    public const int WorldClassFieldNumber = 5;
    private int worldClass_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WorldClass {
      get { return worldClass_; }
      set {
        worldClass_ = value;
      }
    }

    /// <summary>Field number for the "prev_mainlines" field.</summary>
    public const int PrevMainlinesFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_prevMainlines_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> prevMainlines_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> PrevMainlines {
      get { return prevMainlines_; }
    }

    /// <summary>Field number for the "complete_rewards" field.</summary>
    public const int CompleteRewardsFieldNumber = 7;
    private string completeRewards_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CompleteRewards {
      get { return completeRewards_; }
      set {
        completeRewards_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chapter_img" field.</summary>
    public const int ChapterImgFieldNumber = 8;
    private string chapterImg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChapterImg {
      get { return chapterImg_; }
      set {
        chapterImg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chapter_icon" field.</summary>
    public const int ChapterIconFieldNumber = 9;
    private string chapterIcon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChapterIcon {
      get { return chapterIcon_; }
      set {
        chapterIcon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Chapter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Chapter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Desc != other.Desc) return false;
      if (ChapterType != other.ChapterType) return false;
      if (WorldClass != other.WorldClass) return false;
      if(!prevMainlines_.Equals(other.prevMainlines_)) return false;
      if (CompleteRewards != other.CompleteRewards) return false;
      if (ChapterImg != other.ChapterImg) return false;
      if (ChapterIcon != other.ChapterIcon) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (ChapterType != 0) hash ^= ChapterType.GetHashCode();
      if (WorldClass != 0) hash ^= WorldClass.GetHashCode();
      hash ^= prevMainlines_.GetHashCode();
      if (CompleteRewards.Length != 0) hash ^= CompleteRewards.GetHashCode();
      if (ChapterImg.Length != 0) hash ^= ChapterImg.GetHashCode();
      if (ChapterIcon.Length != 0) hash ^= ChapterIcon.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Desc);
      }
      if (ChapterType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ChapterType);
      }
      if (WorldClass != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(WorldClass);
      }
      prevMainlines_.WriteTo(output, _repeated_prevMainlines_codec);
      if (CompleteRewards.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(CompleteRewards);
      }
      if (ChapterImg.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ChapterImg);
      }
      if (ChapterIcon.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ChapterIcon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Desc);
      }
      if (ChapterType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ChapterType);
      }
      if (WorldClass != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(WorldClass);
      }
      prevMainlines_.WriteTo(ref output, _repeated_prevMainlines_codec);
      if (CompleteRewards.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(CompleteRewards);
      }
      if (ChapterImg.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ChapterImg);
      }
      if (ChapterIcon.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ChapterIcon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (ChapterType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChapterType);
      }
      if (WorldClass != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WorldClass);
      }
      size += prevMainlines_.CalculateSize(_repeated_prevMainlines_codec);
      if (CompleteRewards.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CompleteRewards);
      }
      if (ChapterImg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChapterImg);
      }
      if (ChapterIcon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChapterIcon);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Chapter other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.ChapterType != 0) {
        ChapterType = other.ChapterType;
      }
      if (other.WorldClass != 0) {
        WorldClass = other.WorldClass;
      }
      prevMainlines_.Add(other.prevMainlines_);
      if (other.CompleteRewards.Length != 0) {
        CompleteRewards = other.CompleteRewards;
      }
      if (other.ChapterImg.Length != 0) {
        ChapterImg = other.ChapterImg;
      }
      if (other.ChapterIcon.Length != 0) {
        ChapterIcon = other.ChapterIcon;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Desc = input.ReadString();
            break;
          }
          case 32: {
            ChapterType = input.ReadInt32();
            break;
          }
          case 40: {
            WorldClass = input.ReadInt32();
            break;
          }
          case 50:
          case 48: {
            prevMainlines_.AddEntriesFrom(input, _repeated_prevMainlines_codec);
            break;
          }
          case 58: {
            CompleteRewards = input.ReadString();
            break;
          }
          case 66: {
            ChapterImg = input.ReadString();
            break;
          }
          case 74: {
            ChapterIcon = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Desc = input.ReadString();
            break;
          }
          case 32: {
            ChapterType = input.ReadInt32();
            break;
          }
          case 40: {
            WorldClass = input.ReadInt32();
            break;
          }
          case 50:
          case 48: {
            prevMainlines_.AddEntriesFrom(ref input, _repeated_prevMainlines_codec);
            break;
          }
          case 58: {
            CompleteRewards = input.ReadString();
            break;
          }
          case 66: {
            ChapterImg = input.ReadString();
            break;
          }
          case 74: {
            ChapterIcon = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
