// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: daily_shop_reward_receive.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from daily_shop_reward_receive.proto</summary>
  public static partial class DailyShopRewardReceiveReflection {

    #region Descriptor
    /// <summary>File descriptor for daily_shop_reward_receive.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DailyShopRewardReceiveReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9kYWlseV9zaG9wX3Jld2FyZF9yZWNlaXZlLnByb3RvEgVwcm90bxoMcHVi",
            "bGljLnByb3RvUABiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.PublicReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
