// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MallPackage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nova.Client {

  /// <summary>Holder for reflection information generated from MallPackage.proto</summary>
  public static partial class MallPackageReflection {

    #region Descriptor
    /// <summary>File descriptor for MallPackage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MallPackageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNYWxsUGFja2FnZS5wcm90byL6AgoLTWFsbFBhY2thZ2USCgoCaWQYASAB",
            "KAkSDAoEbmFtZRgCIAEoCRIQCghncm91cF9pZBgDIAEoBRIMCgRzb3J0GAQg",
            "ASgFEhUKDWN1cnJlbmN5X3R5cGUYBSABKAUSGAoQY3VycmVuY3lfaXRlbV9p",
            "ZBgGIAEoBRIZChFjdXJyZW5jeV9pdGVtX3F0eRgHIAEoBRINCgVzdG9jaxgI",
            "IAEoBRIUCgxyZWZyZXNoX3R5cGUYCSABKAUSDQoFaXRlbXMYCiABKAkSFgoO",
            "bGlzdF9jb25kX3R5cGUYCyABKAUSGAoQbGlzdF9jb25kX3BhcmFtcxgMIAEo",
            "CRIXCg9vcmRlcl9jb25kX3R5cGUYDSABKAUSGQoRb3JkZXJfY29uZF9wYXJh",
            "bXMYDiABKAkSEQoJbGlzdF90aW1lGA8gASgJEhQKDGRlX2xpc3RfdGltZRgQ",
            "IAEoCRIUCgxkaXNwbGF5X21vZGUYESABKAUSDAoEaWNvbhgSIAEoCUIOqgIL",
            "Tm92YS5DbGllbnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nova.Client.MallPackage), global::Nova.Client.MallPackage.Parser, new[]{ "Id", "Name", "GroupId", "Sort", "CurrencyType", "CurrencyItemId", "CurrencyItemQty", "Stock", "RefreshType", "Items", "ListCondType", "ListCondParams", "OrderCondType", "OrderCondParams", "ListTime", "DeListTime", "DisplayMode", "Icon" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MallPackage : pb::IMessage<MallPackage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MallPackage> _parser = new pb::MessageParser<MallPackage>(() => new MallPackage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MallPackage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nova.Client.MallPackageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MallPackage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MallPackage(MallPackage other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      groupId_ = other.groupId_;
      sort_ = other.sort_;
      currencyType_ = other.currencyType_;
      currencyItemId_ = other.currencyItemId_;
      currencyItemQty_ = other.currencyItemQty_;
      stock_ = other.stock_;
      refreshType_ = other.refreshType_;
      items_ = other.items_;
      listCondType_ = other.listCondType_;
      listCondParams_ = other.listCondParams_;
      orderCondType_ = other.orderCondType_;
      orderCondParams_ = other.orderCondParams_;
      listTime_ = other.listTime_;
      deListTime_ = other.deListTime_;
      displayMode_ = other.displayMode_;
      icon_ = other.icon_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MallPackage Clone() {
      return new MallPackage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "group_id" field.</summary>
    public const int GroupIdFieldNumber = 3;
    private int groupId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GroupId {
      get { return groupId_; }
      set {
        groupId_ = value;
      }
    }

    /// <summary>Field number for the "sort" field.</summary>
    public const int SortFieldNumber = 4;
    private int sort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sort {
      get { return sort_; }
      set {
        sort_ = value;
      }
    }

    /// <summary>Field number for the "currency_type" field.</summary>
    public const int CurrencyTypeFieldNumber = 5;
    private int currencyType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurrencyType {
      get { return currencyType_; }
      set {
        currencyType_ = value;
      }
    }

    /// <summary>Field number for the "currency_item_id" field.</summary>
    public const int CurrencyItemIdFieldNumber = 6;
    private int currencyItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurrencyItemId {
      get { return currencyItemId_; }
      set {
        currencyItemId_ = value;
      }
    }

    /// <summary>Field number for the "currency_item_qty" field.</summary>
    public const int CurrencyItemQtyFieldNumber = 7;
    private int currencyItemQty_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurrencyItemQty {
      get { return currencyItemQty_; }
      set {
        currencyItemQty_ = value;
      }
    }

    /// <summary>Field number for the "stock" field.</summary>
    public const int StockFieldNumber = 8;
    private int stock_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Stock {
      get { return stock_; }
      set {
        stock_ = value;
      }
    }

    /// <summary>Field number for the "refresh_type" field.</summary>
    public const int RefreshTypeFieldNumber = 9;
    private int refreshType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RefreshType {
      get { return refreshType_; }
      set {
        refreshType_ = value;
      }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 10;
    private string items_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Items {
      get { return items_; }
      set {
        items_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "list_cond_type" field.</summary>
    public const int ListCondTypeFieldNumber = 11;
    private int listCondType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ListCondType {
      get { return listCondType_; }
      set {
        listCondType_ = value;
      }
    }

    /// <summary>Field number for the "list_cond_params" field.</summary>
    public const int ListCondParamsFieldNumber = 12;
    private string listCondParams_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ListCondParams {
      get { return listCondParams_; }
      set {
        listCondParams_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "order_cond_type" field.</summary>
    public const int OrderCondTypeFieldNumber = 13;
    private int orderCondType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OrderCondType {
      get { return orderCondType_; }
      set {
        orderCondType_ = value;
      }
    }

    /// <summary>Field number for the "order_cond_params" field.</summary>
    public const int OrderCondParamsFieldNumber = 14;
    private string orderCondParams_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrderCondParams {
      get { return orderCondParams_; }
      set {
        orderCondParams_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "list_time" field.</summary>
    public const int ListTimeFieldNumber = 15;
    private string listTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ListTime {
      get { return listTime_; }
      set {
        listTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "de_list_time" field.</summary>
    public const int DeListTimeFieldNumber = 16;
    private string deListTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeListTime {
      get { return deListTime_; }
      set {
        deListTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "display_mode" field.</summary>
    public const int DisplayModeFieldNumber = 17;
    private int displayMode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DisplayMode {
      get { return displayMode_; }
      set {
        displayMode_ = value;
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 18;
    private string icon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MallPackage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MallPackage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (GroupId != other.GroupId) return false;
      if (Sort != other.Sort) return false;
      if (CurrencyType != other.CurrencyType) return false;
      if (CurrencyItemId != other.CurrencyItemId) return false;
      if (CurrencyItemQty != other.CurrencyItemQty) return false;
      if (Stock != other.Stock) return false;
      if (RefreshType != other.RefreshType) return false;
      if (Items != other.Items) return false;
      if (ListCondType != other.ListCondType) return false;
      if (ListCondParams != other.ListCondParams) return false;
      if (OrderCondType != other.OrderCondType) return false;
      if (OrderCondParams != other.OrderCondParams) return false;
      if (ListTime != other.ListTime) return false;
      if (DeListTime != other.DeListTime) return false;
      if (DisplayMode != other.DisplayMode) return false;
      if (Icon != other.Icon) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (GroupId != 0) hash ^= GroupId.GetHashCode();
      if (Sort != 0) hash ^= Sort.GetHashCode();
      if (CurrencyType != 0) hash ^= CurrencyType.GetHashCode();
      if (CurrencyItemId != 0) hash ^= CurrencyItemId.GetHashCode();
      if (CurrencyItemQty != 0) hash ^= CurrencyItemQty.GetHashCode();
      if (Stock != 0) hash ^= Stock.GetHashCode();
      if (RefreshType != 0) hash ^= RefreshType.GetHashCode();
      if (Items.Length != 0) hash ^= Items.GetHashCode();
      if (ListCondType != 0) hash ^= ListCondType.GetHashCode();
      if (ListCondParams.Length != 0) hash ^= ListCondParams.GetHashCode();
      if (OrderCondType != 0) hash ^= OrderCondType.GetHashCode();
      if (OrderCondParams.Length != 0) hash ^= OrderCondParams.GetHashCode();
      if (ListTime.Length != 0) hash ^= ListTime.GetHashCode();
      if (DeListTime.Length != 0) hash ^= DeListTime.GetHashCode();
      if (DisplayMode != 0) hash ^= DisplayMode.GetHashCode();
      if (Icon.Length != 0) hash ^= Icon.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (GroupId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(GroupId);
      }
      if (Sort != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Sort);
      }
      if (CurrencyType != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(CurrencyType);
      }
      if (CurrencyItemId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(CurrencyItemId);
      }
      if (CurrencyItemQty != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CurrencyItemQty);
      }
      if (Stock != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Stock);
      }
      if (RefreshType != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(RefreshType);
      }
      if (Items.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Items);
      }
      if (ListCondType != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(ListCondType);
      }
      if (ListCondParams.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(ListCondParams);
      }
      if (OrderCondType != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(OrderCondType);
      }
      if (OrderCondParams.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(OrderCondParams);
      }
      if (ListTime.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(ListTime);
      }
      if (DeListTime.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(DeListTime);
      }
      if (DisplayMode != 0) {
        output.WriteRawTag(136, 1);
        output.WriteInt32(DisplayMode);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(Icon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (GroupId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(GroupId);
      }
      if (Sort != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Sort);
      }
      if (CurrencyType != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(CurrencyType);
      }
      if (CurrencyItemId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(CurrencyItemId);
      }
      if (CurrencyItemQty != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CurrencyItemQty);
      }
      if (Stock != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Stock);
      }
      if (RefreshType != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(RefreshType);
      }
      if (Items.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Items);
      }
      if (ListCondType != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(ListCondType);
      }
      if (ListCondParams.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(ListCondParams);
      }
      if (OrderCondType != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(OrderCondType);
      }
      if (OrderCondParams.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(OrderCondParams);
      }
      if (ListTime.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(ListTime);
      }
      if (DeListTime.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(DeListTime);
      }
      if (DisplayMode != 0) {
        output.WriteRawTag(136, 1);
        output.WriteInt32(DisplayMode);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(Icon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (GroupId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GroupId);
      }
      if (Sort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sort);
      }
      if (CurrencyType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrencyType);
      }
      if (CurrencyItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrencyItemId);
      }
      if (CurrencyItemQty != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrencyItemQty);
      }
      if (Stock != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Stock);
      }
      if (RefreshType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RefreshType);
      }
      if (Items.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Items);
      }
      if (ListCondType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ListCondType);
      }
      if (ListCondParams.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ListCondParams);
      }
      if (OrderCondType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrderCondType);
      }
      if (OrderCondParams.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderCondParams);
      }
      if (ListTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ListTime);
      }
      if (DeListTime.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(DeListTime);
      }
      if (DisplayMode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(DisplayMode);
      }
      if (Icon.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MallPackage other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.GroupId != 0) {
        GroupId = other.GroupId;
      }
      if (other.Sort != 0) {
        Sort = other.Sort;
      }
      if (other.CurrencyType != 0) {
        CurrencyType = other.CurrencyType;
      }
      if (other.CurrencyItemId != 0) {
        CurrencyItemId = other.CurrencyItemId;
      }
      if (other.CurrencyItemQty != 0) {
        CurrencyItemQty = other.CurrencyItemQty;
      }
      if (other.Stock != 0) {
        Stock = other.Stock;
      }
      if (other.RefreshType != 0) {
        RefreshType = other.RefreshType;
      }
      if (other.Items.Length != 0) {
        Items = other.Items;
      }
      if (other.ListCondType != 0) {
        ListCondType = other.ListCondType;
      }
      if (other.ListCondParams.Length != 0) {
        ListCondParams = other.ListCondParams;
      }
      if (other.OrderCondType != 0) {
        OrderCondType = other.OrderCondType;
      }
      if (other.OrderCondParams.Length != 0) {
        OrderCondParams = other.OrderCondParams;
      }
      if (other.ListTime.Length != 0) {
        ListTime = other.ListTime;
      }
      if (other.DeListTime.Length != 0) {
        DeListTime = other.DeListTime;
      }
      if (other.DisplayMode != 0) {
        DisplayMode = other.DisplayMode;
      }
      if (other.Icon.Length != 0) {
        Icon = other.Icon;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            GroupId = input.ReadInt32();
            break;
          }
          case 32: {
            Sort = input.ReadInt32();
            break;
          }
          case 40: {
            CurrencyType = input.ReadInt32();
            break;
          }
          case 48: {
            CurrencyItemId = input.ReadInt32();
            break;
          }
          case 56: {
            CurrencyItemQty = input.ReadInt32();
            break;
          }
          case 64: {
            Stock = input.ReadInt32();
            break;
          }
          case 72: {
            RefreshType = input.ReadInt32();
            break;
          }
          case 82: {
            Items = input.ReadString();
            break;
          }
          case 88: {
            ListCondType = input.ReadInt32();
            break;
          }
          case 98: {
            ListCondParams = input.ReadString();
            break;
          }
          case 104: {
            OrderCondType = input.ReadInt32();
            break;
          }
          case 114: {
            OrderCondParams = input.ReadString();
            break;
          }
          case 122: {
            ListTime = input.ReadString();
            break;
          }
          case 130: {
            DeListTime = input.ReadString();
            break;
          }
          case 136: {
            DisplayMode = input.ReadInt32();
            break;
          }
          case 146: {
            Icon = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            GroupId = input.ReadInt32();
            break;
          }
          case 32: {
            Sort = input.ReadInt32();
            break;
          }
          case 40: {
            CurrencyType = input.ReadInt32();
            break;
          }
          case 48: {
            CurrencyItemId = input.ReadInt32();
            break;
          }
          case 56: {
            CurrencyItemQty = input.ReadInt32();
            break;
          }
          case 64: {
            Stock = input.ReadInt32();
            break;
          }
          case 72: {
            RefreshType = input.ReadInt32();
            break;
          }
          case 82: {
            Items = input.ReadString();
            break;
          }
          case 88: {
            ListCondType = input.ReadInt32();
            break;
          }
          case 98: {
            ListCondParams = input.ReadString();
            break;
          }
          case 104: {
            OrderCondType = input.ReadInt32();
            break;
          }
          case 114: {
            OrderCondParams = input.ReadString();
            break;
          }
          case 122: {
            ListTime = input.ReadString();
            break;
          }
          case 130: {
            DeListTime = input.ReadString();
            break;
          }
          case 136: {
            DisplayMode = input.ReadInt32();
            break;
          }
          case 146: {
            Icon = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
