// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: StarTowerRankSeason.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nova.Client {

  /// <summary>Holder for reflection information generated from StarTowerRankSeason.proto</summary>
  public static partial class StarTowerRankSeasonReflection {

    #region Descriptor
    /// <summary>File descriptor for StarTowerRankSeason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StarTowerRankSeasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlTdGFyVG93ZXJSYW5rU2Vhc29uLnByb3RvIugBChNTdGFyVG93ZXJSYW5r",
            "U2Vhc29uEgoKAmlkGAEgASgFEhAKCGdyb3VwX2lkGAIgASgFEhEKCW9wZW5f",
            "dGltZRgDIAEoCRIQCghlbmRfdGltZRgEIAEoCRIOCgZhZmZpeDEYBSABKAUS",
            "EgoKYWZmaXhfYWRkMRgGIAMoBRIOCgZhZmZpeDIYByABKAUSEgoKYWZmaXhf",
            "YWRkMhgIIAMoBRIOCgZhZmZpeDMYCSABKAUSEgoKYWZmaXhfYWRkMxgKIAMo",
            "BRIOCgZhZmZpeDQYCyABKAUSEgoKYWZmaXhfYWRkNBgMIAMoBUIOqgILTm92",
            "YS5DbGllbnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nova.Client.StarTowerRankSeason), global::Nova.Client.StarTowerRankSeason.Parser, new[]{ "Id", "GroupId", "OpenTime", "EndTime", "Affix1", "AffixAdd1", "Affix2", "AffixAdd2", "Affix3", "AffixAdd3", "Affix4", "AffixAdd4" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class StarTowerRankSeason : pb::IMessage<StarTowerRankSeason>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StarTowerRankSeason> _parser = new pb::MessageParser<StarTowerRankSeason>(() => new StarTowerRankSeason());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StarTowerRankSeason> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nova.Client.StarTowerRankSeasonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StarTowerRankSeason() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StarTowerRankSeason(StarTowerRankSeason other) : this() {
      id_ = other.id_;
      groupId_ = other.groupId_;
      openTime_ = other.openTime_;
      endTime_ = other.endTime_;
      affix1_ = other.affix1_;
      affixAdd1_ = other.affixAdd1_.Clone();
      affix2_ = other.affix2_;
      affixAdd2_ = other.affixAdd2_.Clone();
      affix3_ = other.affix3_;
      affixAdd3_ = other.affixAdd3_.Clone();
      affix4_ = other.affix4_;
      affixAdd4_ = other.affixAdd4_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StarTowerRankSeason Clone() {
      return new StarTowerRankSeason(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "group_id" field.</summary>
    public const int GroupIdFieldNumber = 2;
    private int groupId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GroupId {
      get { return groupId_; }
      set {
        groupId_ = value;
      }
    }

    /// <summary>Field number for the "open_time" field.</summary>
    public const int OpenTimeFieldNumber = 3;
    private string openTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OpenTime {
      get { return openTime_; }
      set {
        openTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 4;
    private string endTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EndTime {
      get { return endTime_; }
      set {
        endTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "affix1" field.</summary>
    public const int Affix1FieldNumber = 5;
    private int affix1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Affix1 {
      get { return affix1_; }
      set {
        affix1_ = value;
      }
    }

    /// <summary>Field number for the "affix_add1" field.</summary>
    public const int AffixAdd1FieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_affixAdd1_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> affixAdd1_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> AffixAdd1 {
      get { return affixAdd1_; }
    }

    /// <summary>Field number for the "affix2" field.</summary>
    public const int Affix2FieldNumber = 7;
    private int affix2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Affix2 {
      get { return affix2_; }
      set {
        affix2_ = value;
      }
    }

    /// <summary>Field number for the "affix_add2" field.</summary>
    public const int AffixAdd2FieldNumber = 8;
    private static readonly pb::FieldCodec<int> _repeated_affixAdd2_codec
        = pb::FieldCodec.ForInt32(66);
    private readonly pbc::RepeatedField<int> affixAdd2_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> AffixAdd2 {
      get { return affixAdd2_; }
    }

    /// <summary>Field number for the "affix3" field.</summary>
    public const int Affix3FieldNumber = 9;
    private int affix3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Affix3 {
      get { return affix3_; }
      set {
        affix3_ = value;
      }
    }

    /// <summary>Field number for the "affix_add3" field.</summary>
    public const int AffixAdd3FieldNumber = 10;
    private static readonly pb::FieldCodec<int> _repeated_affixAdd3_codec
        = pb::FieldCodec.ForInt32(82);
    private readonly pbc::RepeatedField<int> affixAdd3_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> AffixAdd3 {
      get { return affixAdd3_; }
    }

    /// <summary>Field number for the "affix4" field.</summary>
    public const int Affix4FieldNumber = 11;
    private int affix4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Affix4 {
      get { return affix4_; }
      set {
        affix4_ = value;
      }
    }

    /// <summary>Field number for the "affix_add4" field.</summary>
    public const int AffixAdd4FieldNumber = 12;
    private static readonly pb::FieldCodec<int> _repeated_affixAdd4_codec
        = pb::FieldCodec.ForInt32(98);
    private readonly pbc::RepeatedField<int> affixAdd4_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> AffixAdd4 {
      get { return affixAdd4_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StarTowerRankSeason);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StarTowerRankSeason other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (GroupId != other.GroupId) return false;
      if (OpenTime != other.OpenTime) return false;
      if (EndTime != other.EndTime) return false;
      if (Affix1 != other.Affix1) return false;
      if(!affixAdd1_.Equals(other.affixAdd1_)) return false;
      if (Affix2 != other.Affix2) return false;
      if(!affixAdd2_.Equals(other.affixAdd2_)) return false;
      if (Affix3 != other.Affix3) return false;
      if(!affixAdd3_.Equals(other.affixAdd3_)) return false;
      if (Affix4 != other.Affix4) return false;
      if(!affixAdd4_.Equals(other.affixAdd4_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (GroupId != 0) hash ^= GroupId.GetHashCode();
      if (OpenTime.Length != 0) hash ^= OpenTime.GetHashCode();
      if (EndTime.Length != 0) hash ^= EndTime.GetHashCode();
      if (Affix1 != 0) hash ^= Affix1.GetHashCode();
      hash ^= affixAdd1_.GetHashCode();
      if (Affix2 != 0) hash ^= Affix2.GetHashCode();
      hash ^= affixAdd2_.GetHashCode();
      if (Affix3 != 0) hash ^= Affix3.GetHashCode();
      hash ^= affixAdd3_.GetHashCode();
      if (Affix4 != 0) hash ^= Affix4.GetHashCode();
      hash ^= affixAdd4_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (GroupId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GroupId);
      }
      if (OpenTime.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OpenTime);
      }
      if (EndTime.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(EndTime);
      }
      if (Affix1 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Affix1);
      }
      affixAdd1_.WriteTo(output, _repeated_affixAdd1_codec);
      if (Affix2 != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Affix2);
      }
      affixAdd2_.WriteTo(output, _repeated_affixAdd2_codec);
      if (Affix3 != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Affix3);
      }
      affixAdd3_.WriteTo(output, _repeated_affixAdd3_codec);
      if (Affix4 != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Affix4);
      }
      affixAdd4_.WriteTo(output, _repeated_affixAdd4_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (GroupId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GroupId);
      }
      if (OpenTime.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OpenTime);
      }
      if (EndTime.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(EndTime);
      }
      if (Affix1 != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Affix1);
      }
      affixAdd1_.WriteTo(ref output, _repeated_affixAdd1_codec);
      if (Affix2 != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Affix2);
      }
      affixAdd2_.WriteTo(ref output, _repeated_affixAdd2_codec);
      if (Affix3 != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Affix3);
      }
      affixAdd3_.WriteTo(ref output, _repeated_affixAdd3_codec);
      if (Affix4 != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Affix4);
      }
      affixAdd4_.WriteTo(ref output, _repeated_affixAdd4_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (GroupId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GroupId);
      }
      if (OpenTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OpenTime);
      }
      if (EndTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EndTime);
      }
      if (Affix1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Affix1);
      }
      size += affixAdd1_.CalculateSize(_repeated_affixAdd1_codec);
      if (Affix2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Affix2);
      }
      size += affixAdd2_.CalculateSize(_repeated_affixAdd2_codec);
      if (Affix3 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Affix3);
      }
      size += affixAdd3_.CalculateSize(_repeated_affixAdd3_codec);
      if (Affix4 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Affix4);
      }
      size += affixAdd4_.CalculateSize(_repeated_affixAdd4_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StarTowerRankSeason other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.GroupId != 0) {
        GroupId = other.GroupId;
      }
      if (other.OpenTime.Length != 0) {
        OpenTime = other.OpenTime;
      }
      if (other.EndTime.Length != 0) {
        EndTime = other.EndTime;
      }
      if (other.Affix1 != 0) {
        Affix1 = other.Affix1;
      }
      affixAdd1_.Add(other.affixAdd1_);
      if (other.Affix2 != 0) {
        Affix2 = other.Affix2;
      }
      affixAdd2_.Add(other.affixAdd2_);
      if (other.Affix3 != 0) {
        Affix3 = other.Affix3;
      }
      affixAdd3_.Add(other.affixAdd3_);
      if (other.Affix4 != 0) {
        Affix4 = other.Affix4;
      }
      affixAdd4_.Add(other.affixAdd4_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            GroupId = input.ReadInt32();
            break;
          }
          case 26: {
            OpenTime = input.ReadString();
            break;
          }
          case 34: {
            EndTime = input.ReadString();
            break;
          }
          case 40: {
            Affix1 = input.ReadInt32();
            break;
          }
          case 50:
          case 48: {
            affixAdd1_.AddEntriesFrom(input, _repeated_affixAdd1_codec);
            break;
          }
          case 56: {
            Affix2 = input.ReadInt32();
            break;
          }
          case 66:
          case 64: {
            affixAdd2_.AddEntriesFrom(input, _repeated_affixAdd2_codec);
            break;
          }
          case 72: {
            Affix3 = input.ReadInt32();
            break;
          }
          case 82:
          case 80: {
            affixAdd3_.AddEntriesFrom(input, _repeated_affixAdd3_codec);
            break;
          }
          case 88: {
            Affix4 = input.ReadInt32();
            break;
          }
          case 98:
          case 96: {
            affixAdd4_.AddEntriesFrom(input, _repeated_affixAdd4_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            GroupId = input.ReadInt32();
            break;
          }
          case 26: {
            OpenTime = input.ReadString();
            break;
          }
          case 34: {
            EndTime = input.ReadString();
            break;
          }
          case 40: {
            Affix1 = input.ReadInt32();
            break;
          }
          case 50:
          case 48: {
            affixAdd1_.AddEntriesFrom(ref input, _repeated_affixAdd1_codec);
            break;
          }
          case 56: {
            Affix2 = input.ReadInt32();
            break;
          }
          case 66:
          case 64: {
            affixAdd2_.AddEntriesFrom(ref input, _repeated_affixAdd2_codec);
            break;
          }
          case 72: {
            Affix3 = input.ReadInt32();
            break;
          }
          case 82:
          case 80: {
            affixAdd3_.AddEntriesFrom(ref input, _repeated_affixAdd3_codec);
            break;
          }
          case 88: {
            Affix4 = input.ReadInt32();
            break;
          }
          case 98:
          case 96: {
            affixAdd4_.AddEntriesFrom(ref input, _repeated_affixAdd4_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
